# Setup
title:        ifsnow's things
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       ifsnow
  url:        https://ifsnow.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown

safe: false
